import type { Metadata } from "next";
import { Inter, Marhey } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/Nav/nav-bar";
import Providers from "@/components/trpc-provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-Inter" });
const vina = Marhey({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-Vina",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          inter.variable,
          vina.variable,
          "relative h-full antialiased"
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Providers>
            <Navbar />
            <div className="flex-grow flex-1">
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                {children}
              </ThemeProvider>
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
